#!/bin/bash

if [ $1 == "--help" ]
then
	printf "Command Example:\n\t./addUser USER1 USER2 USER3 ...\n"
	exit 0
fi

if [ -e gName ]
then
	gName=$(cat gName)
else
	echo "SFTP was not setup!"
	exit 0
fi

for user in $@
do
	sudo useradd -g $gName -s /sbin/nologin -m $user
	printf "\nPASSWORD TO $user\n>> "
	sudo passwd $user
	sudo chmod 700 /home/$user/ && sudo chown $user:$gName /home/$user
done

