#!/bin/bash

echo "INSTALLING DEPENDANCIES"
echo "***********************"
sudo apt update
sudo apt -y install openssh-server openssh-client ssh

echo "ADDING NEW SFTP GROUP"
echo "*********************"
gName=$(hostname)SFTP

sudo addgroup $gName && echo "New group >>> $gName" && echo $gName > gName

printf "Match group $gName\nChrootDirectory /home\nX11Forwarding no\nAllowTcpForwarding no\nForceCommand internal-sftp" >> /etc/ssh/sshd_config
sudo systemctl restart ssh

echo "done"

