#!/bin/bash

if [ -e gName ]
then
	gName=$(cat gName)
else
	echo "SFTP was not setup!"
	exit 0
fi

printf "Match group $gName\nChrootDirectory /home\nX11Forwarding no\nAllowTcpForwarding no\nForceCommand internal-sftp" >> /etc/ssh/sshd_config
sudo systemctl restart ssh
echo "done"

