#!/bin/bash

echo "INSTALLING DEPENDANCIES"
echo "***********************"
if [ $1 == "deb" ]
then
    sudo apt -y install openssh-server ssh
elif [ $1 == "arch" ]
then
    sudo pacman -Syu openssh-server ssh
else
    echo "PLATFORM NOT AVAILABLE!"
    exit 0
fi

echo "ADDING NEW SFTP GROUP"
echo "*********************"
gName=$(hostname)SFTP

sudo addgroup --force-badname $gName && echo "New group >>> $gName" && echo $gName > gName

echo "done"

