#!/bin/bash

echo "INSTALLING DEPENDANCIES"
echo "***********************"
sudo apt -y install openssh-server ssh

echo "ADDING NEW SFTP GROUP"
echo "*********************"
gName=$(hostname)SFTP

sudo addgroup --force-badname $gName && echo "New group >>> $gName" && echo $gName > gName

echo "done"

