#!/bin/bash

createLink() {
	DIR=$(pwd)/$1
	for file in $(ls $DIR)
	do  
        	if [ -f $DIR/$file ]
        	then
                	sudo ln -s $DIR/$file /usr/local/bin
        	fi
	done
}

for dir in sftp
do
	createLink $dir
done

